import { Component } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { CommonModule } from '@angular/common';
import { Product } from './product/product';
import { Filter } from './filter/filter';
import { Search } from './search/search';
import { ProdModel } from '../models/prodModel';
import { ProductDetail } from './product-detail/product-detail';

@Component({
  selector: 'test',
  standalone: true,
  imports: [FormsModule, CommonModule, Product, Filter, Search, ProductDetail],
  templateUrl: './test.html',
  styleUrl: './test.css',
})
export class Test {
  searchText: string = '';
  // searchTextInput(event: any) {
  //   this.searchText = event.target.value;
  // }
  // listOfNumbers: number[] = [2, 5, 8, 7, 15, 9, 52];
  selectedProduct!: ProdModel;
  products = [
    {
      id: 1,
      name: 'Nike React Infinity Run Flyknit',
      description:
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley o",
      brand: 'NIKE',
      gender: 'MEN',
      category: 'RUNNING',
      size: [6, 7, 8, 9, 10],
      color: ['White', 'Blue', 'Black'],
      price: 160,
      // discountPrice: 140,
      is_in_inventory: false,
      items_left: 3,
      imageURL:
        'https://assets.adidas.com/images/h_2000,f_auto,q_auto,fl_lossy,c_fill,g_auto/3bbecbdf584e40398446a8bf0117cf62_9366/Samba_OG_Shoes_White_B75806_01_00_standard.jpg',
      slug: 'nike-react-infinity-run-flyknit',
    },
    {
      id: 2,
      name: 'Adidas Ultraboost 22',
      description: 'Energy return like no other. The ultimate comfort for long distance running.',
      brand: 'ADIDAS',
      gender: 'MEN',
      category: 'RUNNING',
      size: [8, 9, 10, 12],
      color: ['Black', 'Grey', 'Solar Yellow'],
      price: 190,
      discountPrice: 170,
      is_in_inventory: true,
      items_left: 5,
      imageURL: 'https://i8.amplience.net/s/scvl/178735_396397_SET/1?fmt=auto',
      slug: 'adidas-ultraboost-22',
    },
    {
      id: 3,
      name: 'Puma RS-X3 Puzzle',
      description: 'Retro-future design with bold colors and chunky silhouette.',
      brand: 'PUMA',
      gender: 'UNISEX',
      category: 'CASUAL',
      size: [6, 7, 8, 9],
      color: ['Multi', 'White', 'Blue'],
      price: 110,
      // discountPrice: 85,
      is_in_inventory: true,
      items_left: 10,
      imageURL:
        'https://www.converse.com/dw/image/v2/BCZC_PRD/on/demandware.static/-/Sites-cnv-master-catalog/default/dw102c9a96/images/a_08/162050C_A_08X1.jpg',
      slug: 'puma-rs-x3-puzzle',
    },
    {
      id: 4,
      name: 'Nike Air Max 270',
      description:
        'Featuring the first-ever Max Air unit created specifically for Nike Sportswear.',
      brand: 'NIKE',
      gender: 'WOMEN',
      category: 'CASUAL',
      size: [5, 6, 7, 8],
      color: ['Pink', 'White', 'Black'],
      price: 150,
      discountPrice: 130,
      is_in_inventory: true,
      items_left: 2,
      imageURL: 'https://images.asics.com/is/image/asics/1012B047_402_SR_RT_GLB?$zoom$',
      slug: 'nike-air-max-270',
    },
    {
      id: 5,
      name: 'Reebok Nano X2',
      description: 'The most versatile training shoe for cross-functional fitness.',
      brand: 'REEBOK',
      gender: 'MEN',
      category: 'TRAINING',
      size: [8, 9, 10, 11],
      color: ['Core Black', 'Pure Grey'],
      price: 135,
      // discountPrice: 115,
      is_in_inventory: false,
      items_left: 8,
      imageURL:
        'https://assets.adidas.com/images/h_2000,f_auto,q_auto,fl_lossy,c_fill,g_auto/3bbecbdf584e40398446a8bf0117cf62_9366/Samba_OG_Shoes_White_B75806_01_00_standard.jpg',
      slug: 'reebok-nano-x2',
    },
    // ... ادامه محصولات تا ۳۰ مورد با ساختار مشابه
    {
      id: 6,
      name: 'Asics Gel-Kayano 28',
      description: 'Stable and supportive, perfect for overpronators.',
      brand: 'ASICS',
      gender: 'WOMEN',
      category: 'RUNNING',
      size: [6, 7, 8],
      color: ['Blue', 'Lilac'],
      price: 160,
      discountPrice: 145,
      is_in_inventory: true,
      items_left: 4,
      imageURL: 'https://images.asics.com/is/image/asics/1012B047_402_SR_RT_GLB?$zoom$',
      slug: 'asics-gel-kayano-28',
    },
    {
      id: 7,
      name: 'New Balance 574 Classic',
      description: 'Iconic design that meets modern comfort standards.',
      brand: 'NEW BALANCE',
      gender: 'UNISEX',
      category: 'CASUAL',
      size: [7, 8, 9, 10, 11, 12],
      color: ['Navy', 'Grey', 'Burgundy'],
      price: 85,
      // discountPrice: 75,
      is_in_inventory: false,
      items_left: 15,
      imageURL: 'https://i8.amplience.net/s/scvl/178735_396397_SET/1?fmt=auto',
      slug: 'new-balance-574-classic',
    },
    {
      id: 8,
      name: 'Jordan Air Jordan 1 Mid',
      description: 'Inspired by the original AJ1, this mid-top version maintains the iconic look.',
      brand: 'JORDAN',
      gender: 'MEN',
      category: 'BASKETBALL',
      size: [8, 9, 10, 11],
      color: ['Red', 'Black', 'White'],
      price: 125,
      // discountPrice: 125,
      is_in_inventory: true,
      items_left: 1,
      imageURL:
        'https://www.converse.com/dw/image/v2/BCZC_PRD/on/demandware.static/-/Sites-cnv-master-catalog/default/dw102c9a96/images/a_08/162050C_A_08X1.jpg',
      slug: 'jordan-air-jordan-1-mid',
    },
    {
      id: 9,
      name: 'Converse Chuck 70 High Top',
      description: 'The best-ever Chuck 70, built with premium materials.',
      brand: 'CONVERSE',
      gender: 'UNISEX',
      category: 'CASUAL',
      size: [4, 5, 6, 7, 8, 9, 10, 11],
      color: ['Parchment', 'Black', 'Sunflower'],
      price: 90,
      // discountPrice: 80,
      is_in_inventory: true,
      items_left: 20,
      imageURL:
        'https://www.converse.com/dw/image/v2/BCZC_PRD/on/demandware.static/-/Sites-cnv-master-catalog/default/dw102c9a96/images/a_08/162050C_A_08X1.jpg',
      slug: 'converse-chuck-70-high-top',
    },
    {
      id: 10,
      name: 'Under Armour HOVR Phantom 2',
      description: 'Connects to UA MAPMYRUN to track and analyze your running metrics.',
      brand: 'UNDER ARMOUR',
      gender: 'MEN',
      category: 'RUNNING',
      size: [8, 9, 10, 11],
      color: ['Black', 'Red'],
      price: 140,
      discountPrice: 120,
      is_in_inventory: true,
      items_left: 6,
      imageURL:
        'https://assets.adidas.com/images/h_2000,f_auto,q_auto,fl_lossy,c_fill,g_auto/3bbecbdf584e40398446a8bf0117cf62_9366/Samba_OG_Shoes_White_B75806_01_00_standard.jpg',
      slug: 'ua-hovr-phantom-2',
    },
    {
      id: 11,
      name: 'Vans Old Skool',
      description: 'The classic skate shoe and the first to bare the iconic side stripe.',
      brand: 'VANS',
      gender: 'UNISEX',
      category: 'CASUAL',
      size: [5, 6, 7, 8, 9, 10],
      color: ['Black/White', 'Navy'],
      price: 70,
      // discountPrice: 60,
      is_in_inventory: true,
      items_left: 25,
      imageURL: 'https://images.asics.com/is/image/asics/1012B047_402_SR_RT_GLB?$zoom$',
      slug: 'vans-old-skool',
    },
    {
      id: 12,
      name: 'Skechers D-Lites',
      description: 'Classic sporty sneaker design with Air Cooled Memory Foam.',
      brand: 'SKECHERS',
      gender: 'WOMEN',
      category: 'CASUAL',
      size: [6, 7, 8],
      color: ['White', 'Black/Silver'],
      price: 75,
      discountPrice: 65,
      is_in_inventory: true,
      items_left: 12,
      imageURL: 'https://i8.amplience.net/s/scvl/178735_396397_SET/1?fmt=auto',
      slug: 'skechers-d-lites',
    },
    {
      id: 13,
      name: 'Brooks Ghost 14',
      description: 'Balanced, soft cushioning for a smooth ride.',
      brand: 'BROOKS',
      gender: 'MEN',
      category: 'RUNNING',
      size: [9, 10, 11, 12],
      color: ['Black', 'Blue'],
      price: 130,
      // discountPrice: 110,
      is_in_inventory: false,
      items_left: 5,
      imageURL:
        'https://www.converse.com/dw/image/v2/BCZC_PRD/on/demandware.static/-/Sites-cnv-master-catalog/default/dw102c9a96/images/a_08/162050C_A_08X1.jpg',
      slug: 'brooks-ghost-14',
    },
    {
      id: 14,
      name: 'Salomon Speedcross 5',
      description: 'The legendary trail shoe for technical grip and fit.',
      brand: 'SALOMON',
      gender: 'MEN',
      category: 'TRAIL',
      size: [8, 9, 10],
      color: ['Green', 'Black'],
      price: 150,
      discountPrice: 135,
      is_in_inventory: true,
      items_left: 4,
      imageURL: 'https://images.asics.com/is/image/asics/1012B047_402_SR_RT_GLB?$zoom$',
      slug: 'salomon-speedcross-5',
    },
    {
      id: 15,
      name: 'Fila Disruptor II',
      description: 'Premium leather chunky sneakers for a bold look.',
      brand: 'FILA',
      gender: 'WOMEN',
      category: 'CASUAL',
      size: [5, 6, 7],
      color: ['White'],
      price: 95,
      // discountPrice: 65,
      is_in_inventory: false,
      items_left: 9,
      imageURL:
        'https://assets.adidas.com/images/h_2000,f_auto,q_auto,fl_lossy,c_fill,g_auto/3bbecbdf584e40398446a8bf0117cf62_9366/Samba_OG_Shoes_White_B75806_01_00_standard.jpg',
      slug: 'fila-disruptor-ii',
    },
    {
      id: 16,
      name: 'Nike Air Force 1',
      description: 'The legend lives on in the Nike Air Force 1, a modern take on the icon.',
      brand: 'NIKE',
      gender: 'UNISEX',
      category: 'CASUAL',
      size: [6, 7, 8, 9, 10, 11, 12],
      color: ['White', 'Black'],
      price: 110,
      discountPrice: 82,
      is_in_inventory: true,
      items_left: 30,
      imageURL: 'https://images.asics.com/is/image/asics/1012B047_402_SR_RT_GLB?$zoom$',
      slug: 'nike-air-force-1',
    },
    {
      id: 17,
      name: 'Adidas Stan Smith',
      description: 'Timeless style with a sustainable twist.',
      brand: 'ADIDAS',
      gender: 'UNISEX',
      category: 'CASUAL',
      size: [4, 5, 6, 7, 8, 9, 10, 11, 12],
      color: ['White/Green', 'White/Navy'],
      price: 95,
      // discountPrice: 85,
      is_in_inventory: true,
      items_left: 18,
      imageURL: 'https://i8.amplience.net/s/scvl/178735_396397_SET/1?fmt=auto',
      slug: 'adidas-stan-smith',
    },
    {
      id: 18,
      name: 'Mizuno Wave Rider 25',
      description: 'Engineered for responsiveness and smooth transitions.',
      brand: 'MIZUNO',
      gender: 'MEN',
      category: 'RUNNING',
      size: [8, 9, 10, 11],
      color: ['Blue', 'Black/Gold'],
      price: 135,
      discountPrice: 120,
      is_in_inventory: true,
      items_left: 7,
      imageURL:
        'https://www.converse.com/dw/image/v2/BCZC_PRD/on/demandware.static/-/Sites-cnv-master-catalog/default/dw102c9a96/images/a_08/162050C_A_08X1.jpg',
      slug: 'mizuno-wave-rider-25',
    },
    {
      id: 19,
      name: 'Saucony Endorphin Speed 2',
      description: 'For athletes looking for a performance edge on every run.',
      brand: 'SAUCONY',
      gender: 'WOMEN',
      category: 'RUNNING',
      size: [6, 7, 8],
      color: ['Vizipro', 'Black/White'],
      price: 160,
      discountPrice: 140,
      is_in_inventory: true,
      items_left: 3,
      imageURL: 'https://images.asics.com/is/image/asics/1012B047_402_SR_RT_GLB?$zoom$',
      slug: 'saucony-endorphin-speed-2',
    },
    {
      id: 20,
      name: 'Hoka One One Clifton 8',
      description: 'The ultimate everyday trainer for maximum cushioning.',
      brand: 'HOKA',
      gender: 'MEN',
      category: 'RUNNING',
      size: [8, 9, 10, 11, 12],
      color: ['Blue Fog', 'Black'],
      price: 140,
      // discountPrice: 130,
      is_in_inventory: true,
      items_left: 10,
      imageURL:
        'https://assets.adidas.com/images/h_2000,f_auto,q_auto,fl_lossy,c_fill,g_auto/3bbecbdf584e40398446a8bf0117cf62_9366/Samba_OG_Shoes_White_B75806_01_00_standard.jpg',
      slug: 'hoka-clifton-8',
    },
    {
      id: 21,
      name: 'Lacoste Carnaby Evo',
      description: 'Minimalist leather sneakers with the signature crocodile logo.',
      brand: 'LACOSTE',
      gender: 'MEN',
      category: 'CASUAL',
      size: [8, 9, 10],
      color: ['White', 'Navy'],
      price: 100,
      // discountPrice: 90,
      is_in_inventory: false,
      items_left: 5,
      imageURL: 'https://images.asics.com/is/image/asics/1012B047_402_SR_RT_GLB?$zoom$',
      slug: 'lacoste-carnaby-evo',
    },
    {
      id: 22,
      name: 'Merrell Moab 2 Vent',
      description: 'Experience out-of-the-box comfort in this ventilated hiker.',
      brand: 'MERRELL',
      gender: 'MEN',
      category: 'HIKING',
      size: [8, 9, 10, 11, 12],
      color: ['Walnut', 'Black'],
      price: 110,
      discountPrice: 95,
      is_in_inventory: true,
      items_left: 12,
      imageURL: 'https://i8.amplience.net/s/scvl/178735_396397_SET/1?fmt=auto',
      slug: 'merrell-moab-2',
    },
    {
      id: 23,
      name: 'Timberland 6-Inch Premium',
      description: 'The original waterproof boot that started it all.',
      brand: 'TIMBERLAND',
      gender: 'UNISEX',
      category: 'BOOTS',
      size: [6, 7, 8, 9, 10, 11],
      color: ['Wheat', 'Black'],
      price: 190,
      // discountPrice: 180,
      is_in_inventory: false,
      items_left: 8,
      imageURL:
        'https://www.converse.com/dw/image/v2/BCZC_PRD/on/demandware.static/-/Sites-cnv-master-catalog/default/dw102c9a96/images/a_08/162050C_A_08X1.jpg',
      slug: 'timberland-6-inch-premium',
    },
    {
      id: 24,
      name: 'Balenciaga Triple S',
      description: 'The pioneer of the chunky, multi-layered sneaker trend.',
      brand: 'BALENCIAGA',
      gender: 'UNISEX',
      category: 'LUXURY',
      size: [38, 39, 40, 41, 42, 43, 44],
      color: ['White/Grey', 'Black/Red'],
      price: 950,
      discountPrice: 860,
      is_in_inventory: true,
      items_left: 2,
      imageURL: 'https://images.asics.com/is/image/asics/1012B047_402_SR_RT_GLB?$zoom$',
      slug: 'balenciaga-triple-s',
    },
    {
      id: 25,
      name: 'Nike ZoomX Vaporfly NEXT% 2',
      description: 'The fastest shoe in the world for race day.',
      brand: 'NIKE',
      gender: 'MEN',
      category: 'RUNNING',
      size: [8, 9, 10],
      color: ['Volt', 'White/Orange'],
      price: 250,
      discountPrice: 225,
      is_in_inventory: true,
      items_left: 1,
      imageURL:
        'https://assets.adidas.com/images/h_2000,f_auto,q_auto,fl_lossy,c_fill,g_auto/3bbecbdf584e40398446a8bf0117cf62_9366/Samba_OG_Shoes_White_B75806_01_00_standard.jpg',
      slug: 'nike-vaporfly-next-2',
    },
    {
      id: 26,
      name: 'Adidas NMD_R1',
      description: 'Urban exploration sneakers with Boost technology.',
      brand: 'ADIDAS',
      gender: 'UNISEX',
      category: 'CASUAL',
      size: [7, 8, 9, 10, 11],
      color: ['Core Black', 'Cloud White'],
      price: 150,
      // discountPrice: 120,
      is_in_inventory: true,
      items_left: 14,
      imageURL: 'https://images.asics.com/is/image/asics/1012B047_402_SR_RT_GLB?$zoom$',
      slug: 'adidas-nmd-r1',
    },
    {
      id: 27,
      name: 'Puma Suede Classic',
      description: 'The shoe that defined a generation of hip-hop and street style.',
      brand: 'PUMA',
      gender: 'UNISEX',
      category: 'CASUAL',
      size: [6, 7, 8, 9, 10],
      color: ['Black', 'Red', 'Navy'],
      price: 75,
      // discountPrice: 65,
      is_in_inventory: false,
      items_left: 20,
      imageURL: 'https://i8.amplience.net/s/scvl/178735_396397_SET/1?fmt=auto',
      slug: 'puma-suede-classic',
    },
    {
      id: 28,
      name: 'New Balance 990v5',
      description: 'The perfect blend of cushioning and stability.',
      brand: 'NEW BALANCE',
      gender: 'MEN',
      category: 'RUNNING',
      size: [8, 9, 10, 11, 12],
      color: ['Grey', 'Black'],
      price: 185,
      // discountPrice: 185,
      is_in_inventory: true,
      items_left: 5,
      imageURL:
        'https://www.converse.com/dw/image/v2/BCZC_PRD/on/demandware.static/-/Sites-cnv-master-catalog/default/dw102c9a96/images/a_08/162050C_A_08X1.jpg',
      slug: 'new-balance-990v5',
    },
    {
      id: 29,
      name: 'Reebok Club C 85',
      description: 'Clean, minimalist tennis-inspired sneakers.',
      brand: 'REEBOK',
      gender: 'UNISEX',
      category: 'CASUAL',
      size: [5, 6, 7, 8, 9, 10, 11],
      color: ['White/Green', 'Black'],
      price: 75,
      discountPrice: 60,
      is_in_inventory: true,
      items_left: 15,
      imageURL:
        'https://assets.adidas.com/images/h_2000,f_auto,q_auto,fl_lossy,c_fill,g_auto/3bbecbdf584e40398446a8bf0117cf62_9366/Samba_OG_Shoes_White_B75806_01_00_standard.jpg',
      slug: 'reebok-club-c-85',
    },
    {
      id: 30,
      name: 'Dr. Martens 1460',
      description: 'The iconic 8-eye boot made from premium smooth leather.',
      brand: 'DR. MARTENS',
      gender: 'UNISEX',
      category: 'BOOTS',
      size: [5, 6, 7, 8, 9, 10, 11, 12],
      color: ['Black', 'Cherry Red'],
      price: 170,
      // discountPrice: 160,
      is_in_inventory: false,
      items_left: 6,
      imageURL:
        'https://assets.adidas.com/images/h_2000,f_auto,q_auto,fl_lossy,c_fill,g_auto/3bbecbdf584e40398446a8bf0117cf62_9366/Samba_OG_Shoes_White_B75806_01_00_standard.jpg',
      slug: 'dr-martens-1460',
    },
  ];
  totalProductCount = this.products.length;
  totalProductInStock = this.products.filter((p) => p.is_in_inventory === true).length;
  totalProductOutOfStock = this.products.filter((p) => p.is_in_inventory === false).length;

  selectedFilterRadioButton: string = 'all';
  onFilterChange(value: string) {
    this.selectedFilterRadioButton = value;
  }

  setSearchText(el: string) {
    this.searchText = el;
  }
}
